#!/usr/bin/env python3
"""Exact coefficients of Q_a(s) := a zeta(s+1,a)/zeta(s,a) = N_a(s)/D_a(s),
D_a = sum_{n>=0} q_n^{-s}, N_a = sum_{n>=0} q_n^{-1} q_n^{-s}, q_n = 1 + n/a (rational a).
Frequencies lambda = log r, r in the multiplicative monoid M generated by {q_n: n>=1}."""
from fractions import Fraction as Fr
import sys

def coeffs(a, R):
    a = Fr(a)
    gens = []
    n = 1
    while True:
        q = 1 + Fr(n) / a
        if q > R: break
        gens.append(q); n += 1
    Qset = set([Fr(1)] + gens)
    # BFS monoid elements <= R
    M = {Fr(1)}
    frontier = [Fr(1)]
    while frontier:
        new = []
        for x in frontier:
            for q in gens:
                y = x * q
                if y <= R and y not in M:
                    M.add(y); new.append(y)
        frontier = new
    Ms = sorted(M)
    Dinv = {Fr(1): Fr(1)}
    for r in Ms[1:]:
        s = Fr(0)
        for d in gens:
            if d > r: break
            e = r / d
            if e in M:
                s += Dinv[e]
        Dinv[r] = -s
    beta = {}
    for r in Ms:
        s = Dinv[r]                      # d = 1 term: N(1) = 1
        for d in gens:
            if d > r: break
            e = r / d
            if e in M:
                s += Dinv[e] / d
        beta[r] = s
    return Ms, beta, gens

if __name__ == '__main__':
    for a, R in [(1, 30), (Fr(1, 2), 30), (2, 12), (Fr(3, 4), 12)]:
        Ms, beta, gens = coeffs(a, Fr(R))
        print(f"\na = {a}: generators q_n = {[str(q) for q in gens[:8]]} ...")
        for r in Ms[1:18]:
            print(f"   r = {str(r):>7}  (lambda = log r = {float(__import__('math').log(r)):.4f})  beta = {str(beta[r]):>12}  = {float(beta[r]):+.6f}")
