# Checks for 29_ (audit of ETR0-ETR12, EULER_TENSOR_INTAKE_INDEPENDENT_REVIEW.md,
# in the programme's working folder quantum_tau_programme_bridge_20260924).
# claude-ab (Opus 5.5, max effort), 25 September 2026.
import functools
import itertools
import math
import random
from fractions import Fraction

import mpmath as mp
import numpy as np
import sympy as sp

mp.mp.dps = 40
ok_all = True


def report(name, ok, detail=''):
    global ok_all
    ok_all &= bool(ok)
    print(('PASS ' if ok else 'FAIL ') + name + ('  ' + detail if detail else ''))


@functools.lru_cache(maxsize=None)
def Omega(n):
    """Number of prime factors with multiplicity (a completely additive function)."""
    return sum(sp.factorint(n).values())


def formal_log(members):
    """Exact coefficients r_n of log(sum_{n in M} e_n), for a finite initial segment of M.

    Uses the derivation D = Omega (completely additive): Omega(n) d_n = sum_{ab=n} Omega(a) r_a d_b,
    with d = indicator of M. The recursion is exact over the rationals."""
    members = sorted(members)
    S = set(members)
    r = {}
    for n in members:
        if n == 1:
            continue
        acc = Fraction(0)
        for a in members:
            if a == 1 or a >= n:
                continue
            if n % a == 0 and (n // a) in S:
                acc += Omega(a) * r[a]
        r[n] = 1 - acc / Omega(n)
    return r


def monoid_elements(gens, bound):
    elems = {1}
    frontier = [1]
    while frontier:
        new = []
        for x in frontier:
            for g in gens:
                y = x * g
                if y <= bound and y not in elems:
                    elems.add(y)
                    new.append(y)
        frontier = new
    return elems


def atoms_of(elems):
    E = sorted(elems)
    S = set(E)
    at = []
    for n in E:
        if n == 1:
            continue
        if not any(n % a == 0 and (n // a) in S and a != 1 and a != n for a in E if a < n):
            at.append(n)
    return at


def factorizations(n, atoms, start=0):
    """Unordered atom factorizations of n (atoms sorted)."""
    if n == 1:
        return [[]]
    out = []
    for i in range(start, len(atoms)):
        a = atoms[i]
        if a > n:
            break
        if n % a == 0:
            for rest in factorizations(n // a, atoms, i):
                out.append([a] + rest)
    return out


# 1. ETR1.3-ETR1.5 and the sharp example ETR1.6-ETR1.7, on several monoids.
cases = [
    ('<4,8> (ETR1.6; 11_ Example 11.5)', monoid_elements([4, 8], 10 ** 5), Fraction(-1, 6)),
    ('<9,27>', monoid_elements([9, 27], 10 ** 6), Fraction(-1, 6)),
    ('<8,32> (exponents 3,5)', monoid_elements([8, 32], 2 ** 16), Fraction(-7, 15)),
    ('<4,6,9>', monoid_elements([4, 6, 9], 10 ** 4), Fraction(-1, 2)),
    ('n = 1 mod 4 (Hilbert)', {n for n in range(1, 3000) if n % 4 == 1}, Fraction(-1, 2)),
]
ok1 = True
details = []
for name, E, expected in cases:
    r = formal_log(E)
    at = atoms_of(E)
    first_nonUF = None
    for n in sorted(E):
        if n > 1 and len(factorizations(n, at)) >= 2:
            first_nonUF = n
            break
    first_neg = min((n for n in r if r[n] < 0), default=None)
    F = len(factorizations(first_nonUF, at))
    # ETR1.3: r_N = 1 - F(N) + sum over pure-power factorizations a^j = N (j >= 2) of 1/j
    pure = [f for f in factorizations(first_nonUF, at) if len(set(f)) == 1 and len(f) >= 2]
    formula = 1 - F + sum(Fraction(1, len(f)) for f in pure)
    ok = (first_neg == first_nonUF and r[first_nonUF] == formula == expected and formula <= Fraction(-1, 6)
          and all(r[n] >= 0 for n in r if n < first_nonUF))
    ok1 &= ok
    details.append('%s: N=%d, F=%d, r_N=%s' % (name, first_nonUF, F, r[first_nonUF]))
report('1  ETR1.3-1.7: first negative coefficient at the first non-UF element, value 1 - F + sum 1/j, <= -1/6; sharp at 64',
       ok1, '; '.join(details))

# 1b. The F = t = 2 case: r_N = -1 + 1/j1 + 1/j2 over distinct j1, j2 >= 2 is maximal at {2,3}.
vals = sorted(((Fraction(-1) + Fraction(1, a) + Fraction(1, b)), a, b) for a in range(2, 40) for b in range(a + 1, 41))
report('1b ETR1.5: max over distinct j1 < j2 of -1 + 1/j1 + 1/j2 is -1/6, attained only at (2,3)',
       vals[-1] == (Fraction(-1, 6), 2, 3) and vals[-2][0] < Fraction(-1, 6), 'next value %s at %s' % (vals[-2][0], vals[-2][1:]))

# 1c. (29_, Corollary 29.1) At the least non-uniquely factored N with two pure-power factorizations a^j1 = b^j2,
# gcd(j1, j2) = 1 and r_N = -1 + 1/j1 + 1/j2. Every such value occurs (<c^u, c^v>), and a first negative
# coefficient above -1/2 always has this form. Exponent-semigroup computation for M = {2^e : e in S}.
def exp_log(S_gens, E):
    """Formal log of sum_{e in S} x^e for the numerical semigroup S generated by S_gens, up to x^E (exact)."""
    inS = [False] * (E + 1)
    inS[0] = True
    for e in range(1, E + 1):
        inS[e] = any(e >= g and inS[e - g] for g in S_gens)
    d_ = [Fraction(1 if inS[e] else 0) for e in range(E + 1)]
    r_ = [Fraction(0)] * (E + 1)
    for e in range(1, E + 1):
        acc = sum((k * r_[k] * d_[e - k] for k in range(1, e)), Fraction(0))
        r_[e] = d_[e] - acc / e
    return r_
ok1c = True
pairs_done = 0
for u in range(2, 11):
    for v in range(u + 1, 12):
        if math.gcd(u, v) != 1:
            continue
        pairs_done += 1
        r_ = exp_log([u, v], u * v + 2)
        firstneg = next(e for e in range(1, u * v + 3) if r_[e] < 0)
        ok1c &= firstneg == u * v and r_[u * v] == Fraction(-1) + Fraction(1, u) + Fraction(1, v)


def minimal_generators(gens):
    """Atoms of the exponent semigroup generated by gens (the minimal generating set)."""
    g_sorted = sorted(set(gens))
    atoms_ = []
    for g_ in g_sorted:
        # g_ is not an atom if it is a sum of >= 2 nonzero elements of the semigroup generated by the smaller atoms
        reach = {0}
        frontier = {0}
        while frontier:
            new = set()
            for x_ in frontier:
                for a_ in atoms_:
                    y_ = x_ + a_
                    if y_ <= g_ and y_ not in reach:
                        reach.add(y_)
                        new.add(y_)
            frontier = new
        if g_ not in reach:
            atoms_.append(g_)
    return atoms_


def factorizations_exp(E, atoms_, start=0):
    if E == 0:
        return [[]]
    out = []
    for i in range(start, len(atoms_)):
        a_ = atoms_[i]
        if a_ > E:
            break
        for rest in factorizations_exp(E - a_, atoms_, i):
            out.append([a_] + rest)
    return out


# search: all generator sets of size 2 or 3 in [2, 13]. Record the number of distinct semigroups and of sets with gcd > 1.
allowed = {Fraction(-1) + Fraction(1, u) + Fraction(1, v) for u in range(2, 200) for v in range(u + 1, 200) if math.gcd(u, v) == 1}
seen_above = set()
count = 0
semigroups = set()
gcd_gt1 = 0
form_ok = True
for k_ in (2, 3):
    for gens in itertools.combinations(range(2, 14), k_):
        at_ = minimal_generators(gens)
        semigroups.add(tuple(at_))
        if math.gcd(*gens) > 1:
            gcd_gt1 += 1
        r_ = exp_log(list(gens), 170)
        neg = [e for e in range(1, 171) if r_[e] < 0]
        if not neg:
            continue
        count += 1
        E = neg[0]
        val = r_[E]
        facs = factorizations_exp(E, at_)
        # ETR1: first negative at the first exponent with two factorizations
        form_ok &= len(facs) >= 2 and all(len(factorizations_exp(e, at_)) <= 1 for e in range(1, E))
        if val > Fraction(-1, 2):
            seen_above.add(val)
            ok1c &= val in allowed
            # Corollary 29.1: exactly two factorizations, both pure powers a^j1 = b^j2 with gcd(j1, j2) = 1
            pure = [f for f in facs if len(set(f)) == 1]
            ok_form = len(facs) == 2 and len(pure) == 2
            if ok_form:
                j1, j2 = len(pure[0]), len(pure[1])
                ok_form = math.gcd(j1, j2) == 1 and val == Fraction(-1) + Fraction(1, j1) + Fraction(1, j2)
            form_ok &= ok_form
ok1c &= form_ok
predicted = {Fraction(-1, 2) + Fraction(1, v) for v in range(3, 200, 2)} | {Fraction(-5, 12), Fraction(-7, 15)}
ok1c &= seen_above <= predicted
report('1c 29_ Cor. 29.1: <2^u, 2^v> for all %d coprime pairs 2 <= u < v <= 11: first negative -1 + 1/u + 1/v at 2^{uv}; '
       '%d generator sets of size 2-3 in [2,13] (%d distinct semigroups, %d sets with gcd > 1), %d not free: every first value above -1/2 '
       'comes from exactly two pure-power factorizations with coprime exponents and lies in {-1/2 + 1/v, v odd} U {-5/12, -7/15}'
       % (pairs_done, sum(1 for k_ in (2, 3) for _ in itertools.combinations(range(2, 14), k_)), len(semigroups), gcd_gt1, count),
       ok1c, 'values above -1/2 seen: %s' % sorted(seen_above, reverse=True)[:6])

# 2. ETR2.1: for free monoids r_n = 1/j at n = a^j, 0 otherwise; ETR2.2: 0 <= r_n <= 1_M(n).
ok2 = True
for gens, bound in [([2, 6], 10 ** 5), ([3, 5, 7], 10 ** 4), ([4, 5, 6], 10 ** 4)]:
    E = monoid_elements(gens, bound)
    at = atoms_of(E)
    free = all(len(factorizations(n, at)) == 1 for n in E)
    r = formal_log(E)
    pw = {}
    for a in at:
        j, x = 1, a
        while x <= bound:
            pw[x] = Fraction(1, j)
            j += 1
            x *= a
    ok2 &= free and all(r[n] == pw.get(n, 0) for n in r) and all(0 <= r[n] <= 1 for n in r)
report('2  ETR2.1-2.2: free monoids <2,6>, <3,5,7>, <4,5,6>: r_n = 1/j exactly at atom powers, else 0', ok2)

# 2b. The converse of ETR2's zero-freeness fails (11_ Example 11.5): <4,8> is not free, yet
# D(s) = (1 - x + x^2)/(1 - x), x = 2^{-s}, has all its zeros on Re s = 0, the boundary of absolute convergence.
x = sp.symbols('x')
D48 = sp.simplify(1 + x ** 2 / (1 - x))
num = sp.factor(sp.numer(sp.together(D48)))
roots = sp.solve(sp.Eq(num, 0), x)
report('2b <4,8>: D = (1 - x + x^2)/(1 - x) with x = 2^-s; its zeros have |x| = 1, i.e. Re s = 0 (no zero where it converges absolutely)',
       (sp.expand(num - (x ** 2 - x + 1)) == 0 or sp.expand(num + (x ** 2 - x + 1)) == 0) and all(abs(abs(complex(rt)) - 1) < 1e-15 for rt in roots),
       'roots %s' % roots)

# 3. ETR3.2: [e_{p^d r^d}] log D_{q,H} = -(d-1)/2, by the full divisor-lattice computation.
def coeff_at(n, member):
    """Exact log coefficient at n for the monoid given by the membership test, using only divisors of n."""
    divs = sorted(sp.divisors(n))
    Ms = [d for d in divs if member(d)]
    S = set(Ms)
    r = {}
    for m in Ms:
        if m == 1:
            continue
        acc = Fraction(0)
        for a in Ms:
            if a == 1 or a >= m:
                continue
            if m % a == 0 and (m // a) in S:
                acc += Omega(a) * r[a]
        r[m] = 1 - acc / Omega(m)
    return r[n]


ok3 = True
det3 = []
for q, H, p, rr in [(5, {1, 4}, 2, 3), (5, {1}, 2, 7), (7, {1, 2, 4}, 3, 5), (7, {1, 6}, 3, 11), (13, {1}, 2, 41), (8, {1, 7}, 3, 5)]:
    # order d of the coset of p in U(q)/H; p and rr must lie in the same coset
    assert (p * pow(rr, -1, q)) % q in H
    d = 1
    while pow(p, d, q) not in H:
        d += 1
    member = lambda m, q=q, H=H: math.gcd(m, q) == 1 and (m % q) in H
    c = coeff_at(p ** d * rr ** d, member)
    ok3 &= c == Fraction(-(d - 1), 2)
    det3.append('q=%d,d=%d:%s' % (q, d, c))
report('3  ETR3.2: coefficient -(d-1)/2 at p^d r^d for six (q, H, p, r)', ok3, ', '.join(det3))

# 4. ETR4.5-4.7: tensor determinant with nilpotents, and the nilpotency index / top coefficient ETR4.6.
random.seed(29)
np.random.seed(29)


def W_block(omega, m, n):
    N = np.diag(np.ones(m - 1), -1)  # multiplication by epsilon on C[e]/(e^m) in the basis 1, e, ..., e^{m-1}
    E = np.zeros((m, m), dtype=complex)
    P = np.eye(m)
    for a in range(m):
        E += (math.log(n) ** a / math.factorial(a)) * P
        P = P @ N
    return (n ** omega) * E


def block_diag(mats):
    D = sum(M.shape[0] for M in mats)
    out = np.zeros((D, D), dtype=complex)
    i = 0
    for M in mats:
        k = M.shape[0]
        out[i:i + k, i:i + k] = M
        i += k
    return out


omegas = [0.31 + 0.7j, 0.31 - 0.7j, 0.12 + 0.0j]
ms = [2, 3, 1]
n = 6
W = block_diag([W_block(w, m, n) for w, m in zip(omegas, ms)])
err4 = 0.0
for d in [1, 2, 3]:
    Wd = W
    for _ in range(d - 1):
        Wd = np.kron(Wd, W)
    for U in [0.13 + 0.05j, -0.2 + 0.11j]:
        lhs = np.linalg.det(np.eye(Wd.shape[0]) - U * Wd)
        rhs = 1.0 + 0j
        for tup in itertools.product(range(3), repeat=d):
            sig = sum(omegas[i] for i in tup)
            M = np.prod([ms[i] for i in tup])
            rhs *= (1 - U * n ** sig) ** M
        err4 = max(err4, abs(lhs - rhs) / abs(rhs))
# nilpotency index and top coefficient on C[x1..xd]/(x_a^{m_a})
ok4b = True
for mm in [(2, 3), (3, 3, 2), (4, 1, 2)]:
    xs = sp.symbols('x1:%d' % (len(mm) + 1))
    L = sum(m - 1 for m in mm)

    def trunc(expr):
        P = sp.Poly(sp.expand(expr), *xs)
        return sum(c * sp.prod([xs[k] ** e[k] for k in range(len(xs))]) for e, c in P.terms() if all(e[k] < mm[k] for k in range(len(xs))))
    s = sum(xs)
    top = trunc(s ** L)
    coeff = sp.Poly(top, *xs).coeff_monomial(sp.prod([xs[k] ** (mm[k] - 1) for k in range(len(xs))])) if top != 0 else 0
    ok4b &= trunc(s ** (L + 1)) == 0 and coeff == sp.factorial(L) / sp.prod([sp.factorial(m - 1) for m in mm])
report('4  ETR4.7: det(1 - U W_n^{(x)d}) = prod (1 - U n^sigma)^M with jets (m = 2,3,1), d = 1,2,3; ETR4.6 nilpotency index and top coefficient',
       err4 < 1e-10 and ok4b, 'max rel err %.1e' % err4)

# 5. ETR5.3: Euler product of the tensor determinant equals the product of shifted original zeta functions.
# mu = delta_{w} + delta_{conj w} (with jets of length 2 and 1), d = 2, s = 4 + 0.3i; primes up to 2*10^5, tail bounded.
w = mp.mpc('0.3', '0.9')
om = [w, mp.conj(w)]
mm5 = [2, 1]
d = 2
s = mp.mpc(4, '0.3')
logE = mp.mpc(0)
P = 200000
primes = list(sp.primerange(2, P))
tuples = list(itertools.product(range(2), repeat=d))
for p in primes:
    for tup in tuples:
        sig = sum(om[i] for i in tup)
        M = 1
        for i in tup:
            M *= mm5[i]
        logE += -M * mp.log(1 - mp.power(p, sig - s))
lhs = mp.exp(logE)
rhs = mp.mpf(1)
for tup in tuples:
    sig = sum(om[i] for i in tup)
    M = 1
    for i in tup:
        M *= mm5[i]
    rhs *= mp.zeta(s - sig) ** M
delta = s.real - d * mp.mpf('0.3')
tail = 9 * 2 * mp.mpf(P) ** (1 - delta) / (delta - 1)  # D^d * sum_{p>P} p^{-delta}(1-2^-delta)^{-1}, crude
e5 = abs(lhs - rhs) / abs(rhs)
# the same with the operator built explicitly: W_p on V = J_w (+) J_conj(w) (jet lengths 2 and 1), W_p^{(x)2} (9 x 9),
# log det(I - p^{-s} W_p^{(x)2}) by numpy per prime (double precision)
wc = complex(w)
sc = complex(s)
logdet_sum = 0j
for p in primes:
    Wp = block_diag([W_block(wc, 2, p), W_block(wc.conjugate(), 1, p)])
    W2 = np.kron(Wp, Wp)
    sign, ld = np.linalg.slogdet(np.eye(9) - p ** (-sc) * W2)
    logdet_sum += ld + np.log(sign)
lhs_op = mp.exp(-mp.mpc(logdet_sum))
e5op = abs(lhs_op - rhs) / abs(rhs)
report('5  ETR5.3: prod_p det(1 - p^-s W_p^{(x)2})^-1 = prod zeta(s - sigma)^M (primes < 2e5), both from the grouped factors and from the explicit 9x9 operator W_p^{(x)2} with a length-2 jet',
       e5 < 2 * tail and e5op < 2 * tail + 1e-12,
       'rel err grouped %.2e, explicit operator %.2e, tail bound %.2e' % (e5, e5op, tail))

# 6. ETR5.6-5.9: the recurrence v a(v) = sum T(r)^{2k} a(v-r) gives the coefficients of prod (1 - U p^sigma)^{-M}; a(v) >= 0.
ok6 = True
err6 = 0
for k in [1, 2]:
    for p in [2, 3, 5]:
        # conjugation-stable exponent data: w, conj w (mult 2 each, jets allowed) and a real 0.2 (mult 1)
        ex = [(mp.mpc('0.25', '1.3'), 2), (mp.mpc('0.25', '-1.3'), 2), (mp.mpf('0.2'), 1)]
        T = lambda r: sum(m * mp.power(p, r * e) for e, m in ex)
        V = 10
        a = [mp.mpf(1)]
        for v in range(1, V + 1):
            a.append(sum(T(r) ** (2 * k) * a[v - r] for r in range(1, v + 1)) / v)
        # direct expansion: log det(...)^{-1} = sum_r tr(W^{(x)2k r}) U^r / r with tr = T(r)^{2k}; compare with the product over tuples
        Useries = [mp.mpf(1)] + [mp.mpf(0)] * V
        for tup in itertools.product(range(3), repeat=2 * k):
            sig = sum(ex[i][0] for i in tup)
            M = 1
            for i in tup:
                M *= ex[i][1]
            x_ = mp.power(p, sig)
            # multiply the series by (1 - x U)^{-M}
            for _ in range(M):
                for v in range(1, V + 1):
                    Useries[v] += x_ * Useries[v - 1]
        err6 = max(err6, max(abs(Useries[v] - a[v]) / (1 + abs(a[v])) for v in range(V + 1)))
        ok6 &= all(abs(mp.im(av)) < mp.mpf(10) ** -30 * (1 + abs(av)) and mp.re(av) >= 0 for av in a)
report('6  ETR5.6-5.9: recurrence coefficients = expansion of prod (1 - U p^sigma)^{-M}; all a_p(v) >= 0 (k = 1, 2; p = 2, 3, 5)',
       ok6 and err6 < 1e-25, 'max rel err %.1e' % err6)

# 7. ETR6.5 and ETR7.3: resonance multiplicities by enumeration = multinomial formula = torus integral (rank 2).
B = Fraction(3, 10)
gam = [(1, 0), (-1, 0), (2, 0), (-2, 0), (0, 1), (0, -1)]  # coordinates v_j in Z^2 (the second generator plays sqrt 2)
bmult = [1, 1, 2, 2, 1, 1]
ok7 = True
det7 = []
for dd in [2, 4, 6]:
    # enumeration over ordered tuples of basis vectors of the total space (each exponent j has b_j labelled copies)
    labelled = [j for j in range(len(gam)) for _ in range(bmult[j])]
    cnt = {}
    for tup in itertools.product(labelled, repeat=dd):
        eta = (sum(gam[j][0] for j in tup), sum(gam[j][1] for j in tup))
        cnt[eta] = cnt.get(eta, 0) + 1
    # multinomial formula (ETR6.5)
    form = {}
    for comp in itertools.product(range(dd + 1), repeat=len(gam)):
        if sum(comp) != dd:
            continue
        eta = (sum(c * g[0] for c, g in zip(comp, gam)), sum(c * g[1] for c, g in zip(comp, gam)))
        val = math.factorial(dd)
        den = 1
        for c in comp:
            den *= math.factorial(c)
        val = val // den
        for c, b in zip(comp, bmult):
            val *= b ** c
        form[eta] = form.get(eta, 0) + val
    # torus integral of f^dd on a 32 x 32 grid (exact for trigonometric polynomials of degree < 32)
    G = 32
    th = 2 * np.pi * np.arange(G) / G
    T1, T2 = np.meshgrid(th, th, indexing='ij')
    f = sum(b * np.exp(1j * (g[0] * T1 + g[1] * T2)) for g, b in zip(gam, bmult))
    h_int = np.mean(f ** dd).real
    ok7 &= cnt == form and abs(h_int - cnt[(0, 0)]) < 1e-6 * cnt[(0, 0)] and np.max(np.abs(f.imag)) < 1e-12
    det7.append('d=%d: h=%d' % (dd, cnt[(0, 0)]))
report('7  ETR6.5 = direct tuple count = ETR7.3 torus integral (frequencies +-1, +-2, +-sqrt2 with multiplicities 1,2,1)', ok7, ', '.join(det7))

# 8. ETR7.4-7.6: h_{2k}^{1/2k} nondecreasing with limit D_B; the quartet case h_{2k} = m^{2k} C(2k,k) -> 2m.
ok8 = True
for m in [1, 2, 3]:
    roots = [mp.power(m ** (2 * k) * mp.binomial(2 * k, k), mp.mpf(1) / (2 * k)) for k in range(1, 400)]
    ok8 &= all(roots[i] <= roots[i + 1] for i in range(len(roots) - 1)) and abs(roots[-1] - 2 * m) < 0.02 * m and roots[-1] < 2 * m
# the rank-2 example above: D_B = 8, and the roots increase toward 8
labelled = [j for j in range(len(gam)) for _ in range(bmult[j])]
G = 64
th = 2 * np.pi * np.arange(G) / G
T1, T2 = np.meshgrid(th, th, indexing='ij')
f = sum(b * np.exp(1j * (g[0] * T1 + g[1] * T2)) for g, b in zip(gam, bmult)).real
hs = [np.mean(f ** (2 * k)) ** (1 / (2 * k)) for k in range(1, 15)]
ok8 &= all(hs[i] <= hs[i + 1] + 1e-12 for i in range(len(hs) - 1)) and hs[-1] < 8 and np.max(np.abs(f)) <= 8 + 1e-12
report('8  ETR7.4-7.6: roots h^{1/2k} nondecreasing, below D_B, -> 2m for the quartet; rank-2 example below D_B = 8',
       ok8, 'rank-2 roots k=1..14: %.3f ... %.3f' % (hs[0], hs[-1]))

# 9. ETR6.7: leading Laurent coefficient at alpha = 1 + 2kB is the product of the remaining zeta values, and it is > 0.
Bv = mp.mpf('0.4')
g9 = mp.mpf('3.7')
b0 = mp.mpf('0.1')
ex9 = [mp.mpc(Bv, g9), mp.mpc(Bv, -g9), mp.mpc(b0, 0)]
dd = 2
alpha = 1 + dd * Bv
cnt9 = {}
for tup in itertools.product(range(3), repeat=dd):
    sig = sum(ex9[i] for i in tup)
    key = (mp.nstr(sig.real, 20), mp.nstr(sig.imag, 20))
    cnt9[key] = (sig, cnt9.get(key, (sig, 0))[1] + 1)
h9 = [c for (sig, c) in cnt9.values() if abs(sig - dd * Bv) < 1e-30][0]
lead = mp.mpf(1)
for sig, c in cnt9.values():
    if abs(sig - dd * Bv) > 1e-30:
        lead *= mp.zeta(alpha - sig) ** c
L9 = lambda s: mp.fprod([mp.zeta(s - sig) ** c for sig, c in cnt9.values()])
eps = mp.mpf('1e-12')
approx = eps ** h9 * L9(alpha + eps)
e9 = abs(approx - lead) / abs(lead)
report('9  ETR6.7: (s - alpha)^h L(s) -> prod zeta(alpha - sigma)^c > 0 (B = 0.4, gamma = 3.7, extra real exponent 0.1; h = %d)' % h9,
       e9 < 1e-9 and abs(mp.im(lead)) < 1e-30 and mp.re(lead) > 0, 'lead %s, rel err %.1e' % (mp.nstr(mp.re(lead), 12), e9))

# 10. ETR8: collision at one prime only; Z_C != 1 for C = delta_0 - delta_{2 pi i/log 2}; Vandermonde determinant.
t = 2 * mp.pi / mp.log(2)
col2 = abs(mp.power(2, mp.mpc(0, t)) - 1)
col3 = abs(mp.power(3, mp.mpc(0, t)) - 1)
Zc = mp.zeta(3) / mp.zeta(mp.mpc(3, -t))
xs10 = [mp.mpc(random.uniform(-2, 2), random.uniform(-2, 2)) for _ in range(5)]
Vm = mp.matrix([[xj ** (r + 1) for xj in xs10] for r in range(5)])
vdet = mp.fprod(xs10) * mp.fprod([xs10[j] - xs10[i] for i in range(5) for j in range(i + 1, 5)])
e10 = abs(mp.det(Vm) - vdet) / abs(vdet)
report('10 ETR8.4-8.5: 2^{it} = 1 but 3^{it} != 1 for t = 2pi/log2; Z_C(3) != 1; det(x_j^r) = prod x_j * Vandermonde',
       col2 < 1e-35 and col3 > 0.1 and abs(Zc - 1) > 0.01 and e10 < 1e-30, '|3^it - 1| = %.3f, |Z_C(3) - 1| = %.3f' % (col3, abs(Zc - 1)))

# 11. ETR9.5: moment recursion recovers M_j from S_j = sum c_d(sigma) sigma^j (exact, Gaussian rationals), d = 3.
I = sp.I
mu = {sp.Rational(1, 3) + 2 * I: 2, sp.Rational(1, 3) - 2 * I: 2, sp.Rational(-1, 5): 1, sp.Rational(1, 2) + I / 7: 3}
d11 = 3
cd = {}
for tup in itertools.product(list(mu.keys()), repeat=d11):
    sig = sp.expand(sum(tup))
    cd[sig] = cd.get(sig, 0) + sp.prod([mu[w_] for w_ in tup])
Mtrue = [sp.expand(sum(c * w_ ** j for w_, c in mu.items())) for j in range(8)]
S = [sp.expand(sum(c * s_ ** j for s_, c in cd.items())) for j in range(8)]
Mrec = [sp.Integer(round(float(S[0]) ** (1.0 / d11)))]
for j in range(1, 8):
    rest = 0
    for comp in itertools.product(range(j), repeat=d11):
        if sum(comp) == j:
            term = sp.factorial(j)
            for a_ in comp:
                term /= sp.factorial(a_)
            rest += term * sp.prod([Mrec[a_] for a_ in comp])
    Mrec.append(sp.expand((S[j] - rest) / (d11 * Mrec[0] ** (d11 - 1))))
report('11 ETR9.5: exact recursive recovery of the moments M_0..M_7 from the d = 3 convolution moments',
       all(sp.simplify(Mrec[j] - Mtrue[j]) == 0 for j in range(8)), 'M_0 = %s' % Mrec[0])

# 12. ETR10: the jet J and the split S have identical tensor Euler data but non-isomorphic operators; ETR10.5 rank m - 1.
om10 = mp.mpc('0.2', '0.5')
okJ = True
for nn in [2, 3, 10]:
    WJ = W_block(complex(om10), 2, nn)
    WS = (nn ** complex(om10)) * np.eye(2)
    okJ &= np.linalg.matrix_rank(WJ - nn ** complex(om10) * np.eye(2), tol=1e-9) == 1
    okJ &= np.linalg.matrix_rank(WS - nn ** complex(om10) * np.eye(2), tol=1e-9) == 0
    for U in [0.1, 0.05 + 0.02j]:
        okJ &= abs(np.linalg.det(np.eye(2) - U * WJ) - np.linalg.det(np.eye(2) - U * WS)) < 1e-12
ok10 = True
for m in [1, 2, 3, 5]:
    for p in [2, 3, 7]:
        Wp = W_block(0.3 + 0.8j, m, p)
        N = np.diag(np.ones(m - 1), -1) if m > 1 else np.zeros((1, 1))
        Dm = Wp @ N - (1 / p) * N @ Wp
        ok10 &= np.allclose(Dm, (1 - 1 / p) * Wp @ N) and np.linalg.matrix_rank(Dm, tol=1e-9) == m - 1
report('12 ETR10.1-10.4: same determinants, ranks 1 vs 0; ETR10.5: W_p N - p^-1 N W_p = (1 - p^-1) W_p N of rank m - 1', okJ and ok10)

# 13. ETR11.1: functional equation; eta(s) > 0 and 1 - 2^{1-s} < 0 on (0,1); ETR11.3 arithmetic.
s13 = mp.mpc('0.37', '14.2')
fe = 2 ** s13 * mp.pi ** (s13 - 1) * mp.sin(mp.pi * s13 / 2) * mp.gamma(1 - s13) * mp.zeta(1 - s13)
e13 = abs(fe - mp.zeta(s13)) / abs(mp.zeta(s13))
etas = [mp.altzeta(sv) for sv in mp.linspace(0.01, 0.99, 50)]
kk = sp.symbols('k')
Bs = sp.symbols('B')
report('13 ETR11.1 functional equation; eta > 0 and zeta < 0 on (0,1); (1 + 2kB) - (k + 1) = k(2B - 1)',
       e13 < 1e-30 and all(e > 0 for e in etas) and all(mp.zeta(sv) < 0 for sv in mp.linspace(0.01, 0.99, 50))
       and sp.expand((1 + 2 * kk * Bs) - (kk + 1) - kk * (2 * Bs - 1)) == 0, 'FE rel err %.1e' % e13)

# 14. (29_, Negative result 29.N2) No finite set of primes suffices in ETR8: for S = {2, 3} the products
# Z_C = zeta(s) zeta(s - a - b) and Z_C' = zeta(s - a) zeta(s - b), a = 2 pi i/log 2, b = 2 pi i/log 3,
# have identical Euler factors at 2 and at 3, but differ at 5 and as functions (ETR8 then applies with p = 5).
a14 = mp.mpc(0, 2 * mp.pi / mp.log(2))
b14 = mp.mpc(0, 2 * mp.pi / mp.log(3))
s14 = mp.mpc('2.5', '0.7')
def local(p, shifts):
    return mp.fprod([1 / (1 - mp.power(p, sh - s14)) for sh in shifts])
C14 = [0, a14 + b14]
Cp14 = [a14, b14]
e14 = max(abs(local(p, C14) - local(p, Cp14)) for p in [2, 3])
d14 = abs(local(5, C14) - local(5, Cp14))
Zdiff = abs(mp.fprod([mp.zeta(s14 - sh) for sh in C14]) - mp.fprod([mp.zeta(s14 - sh) for sh in Cp14]))
# general k: the signed measure sum_eps (-1)^|eps| delta_{sigma_eps} has Laplace transform prod_j (1 - e^{a_j z}), nonzero
z = mp.mpc('0.3', '0.2')
aa = [mp.mpc(0, 2 * mp.pi / mp.log(p)) for p in [2, 3, 5]]
lap = mp.fsum([(-1) ** sum(eps) * mp.exp(sum(e_ * a_ for e_, a_ in zip(eps, aa)) * z) for eps in itertools.product([0, 1], repeat=3)])
prodf = mp.fprod([1 - mp.exp(a_ * z) for a_ in aa])
# and its local data vanishes at 2, 3, 5: sum_eps (-1)^|eps| p^{r sigma_eps} = 0 for r = 1..4
loc0 = max(abs(mp.fsum([(-1) ** sum(eps) * mp.power(p, r * sum(e_ * a_ for e_, a_ in zip(eps, aa))) for eps in itertools.product([0, 1], repeat=3)]))
           for p in [2, 3, 5] for r in range(1, 5))
loc7 = abs(mp.fsum([(-1) ** sum(eps) * mp.power(7, sum(e_ * a_ for e_, a_ in zip(eps, aa))) for eps in itertools.product([0, 1], repeat=3)]))
report('14 29_ N2: equal Euler factors at 2 and 3, different at 5 and globally; k = 3 box: local data 0 at 2, 3, 5, Laplace transform = prod (1 - e^{a_j z}) != 0',
       e14 < 1e-35 and d14 > 1e-3 and Zdiff > 1e-3 and abs(lap - prodf) < 1e-35 and abs(prodf) > 1e-3 and loc0 < 1e-30 and loc7 > 1e-3,
       'max diff at 2,3: %.1e; at 5: %.3f; |Z_C - Z_C\'| at s = 2.5+0.7i: %.3f; box at 7: %.3f' % (e14, d14, Zdiff, loc7))

print('ALL PASS' if ok_all else 'SOME CHECK FAILED')
