# claude-ab independent checks of copy-newresults round 2: Theorem D identity; exact beta_r(2) values.
import mpmath as mp
from fractions import Fraction as Fr
mp.mp.dps = 30
ok = True
# (i) Theorem D: arg zeta'(rho_n) = pi*S_n (mod 2pi), S_n = n - 3/2 - theta(gamma_n)/pi,
#     and arg c1 = pi/2 - phi_n + pi*(S32 - S_n), S32 = arg zeta(3/2+i gamma)/pi (principal value)
worst1 = worst2 = 0
for n in range(1, 41):
    rho = mp.zetazero(n); g = rho.imag
    zp = mp.zeta(rho, derivative=1)
    Sn = n - mp.mpf(3)/2 - mp.siegeltheta(g)/mp.pi
    d1 = (mp.arg(zp) - mp.pi*Sn) / (2*mp.pi); d1 = abs(d1 - mp.nint(d1))
    c1 = rho*mp.zeta(rho+1)/zp
    S32 = mp.arg(mp.zeta(mp.mpf(3)/2 + 1j*g))/mp.pi
    phin = mp.atan(1/(2*g))
    d2 = (mp.arg(c1) - (mp.pi/2 - phin + mp.pi*(S32 - Sn))) / (2*mp.pi); d2 = abs(d2 - mp.nint(d2))
    worst1 = max(worst1, d1); worst2 = max(worst2, d2)
print("Theorem D, n<=40: max |arg zeta'(rho)-pi S_n| (in turns) =", mp.nstr(worst1, 3), "; max |arg c1 - formula| =", mp.nstr(worst2, 3))
ok &= worst1 < 1e-20 and worst2 < 1e-20
# (ii) exact beta_r(a) at a = 2: Q(s) = G(s+1)/G(s), G(s) = sum_{n>=0} q_n^{-s}, q_n = 1 + n/a.
#     Work in the algebra of generalized Dirichlet series with rational frequencies r (coefficient dict), truncated at r <= R.
a = Fr(2); R = Fr(8)
q = [1 + Fr(n)/a for n in range(0, 40) if 1 + Fr(n)/a <= R]
G = {qq: Fr(1) for qq in q}                  # coefficients of G(s)
Gs1 = {qq: 1/qq for qq in q}                 # G(s+1): coefficient q^{-1} at frequency q
def mul(A, B):
    C = {}
    for x, u in A.items():
        for y, v in B.items():
            z = x*y
            if z <= R: C[z] = C.get(z, 0) + u*v
    return C
# inverse of G: solve H with H*G = delta_1 by recursion over sorted frequencies of the monoid generated by q
freqs = {Fr(1)}
frontier = [Fr(1)]
while frontier:
    new = []
    for x in frontier:
        for qq in q[1:]:
            z = x*qq
            if z <= R and z not in freqs: freqs.add(z); new.append(z)
    frontier = new
freqs = sorted(freqs)
Hinv = {}
for r in freqs:
    if r == 1: Hinv[r] = Fr(1); continue
    s = Fr(0)
    for x, u in Hinv.items():
        y = r / x
        if y in G and x != r: s += u*G[y]
    Hinv[r] = -s
beta = mul(Gs1, Hinv)
want = {Fr(3,2): Fr(-1,3), Fr(2): Fr(-1,2), Fr(9,4): Fr(1,3), Fr(5,2): Fr(-3,5), Fr(3): Fr(1,6),
        Fr(15,4): Fr(14,15), Fr(21,4): Fr(22,21), Fr(45,8): Fr(-19,15), Fr(6): Fr(1,12)}
for r, v in want.items():
    got = beta.get(r, Fr(0)); ok &= (got == v)
    print(f"beta_{r}(2) = {got}  (copy: {v})")
print("ALL PASS" if ok else "FAILURE")
