import sympy as sp
x, y, w, tau = sp.symbols('x y w tau')
F = sp.Matrix([(1 + x*y)**3*w + y**2*(1 + x*y)*(4 + 3*x*y), y + 3*x*(1 + x*y)**2*w + 3*x*y**2*(4 + 3*x*y), 2*x - 3*x**2*y - x**3*w])
J = F.jacobian([x, y, w])
print("det DF =", sp.simplify(J.det()))
for pt in [(0, 0, sp.Rational(-1, 4)), (1, sp.Rational(-3, 2), sp.Rational(13, 2)), (-1, sp.Rational(3, 2), sp.Rational(13, 2))]:
    print(pt, "->", list(F.subs({x: pt[0], y: pt[1], w: pt[2]})))
sol = sp.solve(list(F - sp.Matrix([sp.Rational(-1, 4), 0, 0])), [x, y, w], dict=True)
print("all preimages of (-1/4,0,0):", sol)
z = sp.sqrt(1 - 8*tau)
g = sp.Matrix([1/z, -3*z/2, 13*z**2/2])
print("F(gamma(tau)) =", [sp.simplify(e) for e in F.subs({x: g[0], y: g[1], w: g[2]})])
# the flow: gamma' = DF(gamma)^{-1} c for constant c = (2,0,0)
res = J.subs({x: g[0], y: g[1], w: g[2]}) * g.diff(tau) - sp.Matrix([2, 0, 0])
print("DF(gamma) gamma' - (2,0,0) =", [sp.simplify(e) for e in res])
V = J.inv() * sp.Matrix([2, 0, 0])
print("div of V = DF^{-1}(2,0,0):", sp.simplify(sum(sp.diff(V[i], v) for i, v in enumerate([x, y, w]))), " polynomial:", all(sp.simplify(e).is_polynomial(x, y, w) for e in V))
# curvature identity for A_i = lam u_i T, T = -i sigma_3/2: tr T^2 = -1/2
T = sp.Matrix([[-sp.I/2, 0], [0, sp.I/2]])
print("tr T^2 =", (T*T).trace())
