# Referee 21 (wbreader): ES-09 (3,4,inf) covers -- relations, orbits and genera from cycle counts.
# Independent code from the displayed matrices / affine maps of es_s6_counterfactual/src/core.tex.
from fractions import Fraction as Fr
import numpy as np
A1=np.array([[1,0,0,0],[6,0,1,0],[-6,-1,-1,0],[-2,1,0,1]])
A2=np.array([[1,0,0,0],[0,0,-1,0],[-6,1,0,0],[3,0,1,1]])
Ai=np.array([[1,0,0,0],[0,1,0,0],[0,1,1,0],[-1,0,0,1]])
I=np.eye(4,dtype=int)
print("A1^3=I", (np.linalg.matrix_power(A1,3)==I).all(), " A2^4=I", (np.linalg.matrix_power(A2,4)==I).all(), " A1A2Ainf=I", (A1@A2@Ai==I).all())
def a1(p,D): x,y,z=p; return ((6+y)%D,(-6-x-y)%D,(z-2+x)%D)
def a2(p,D): x,y,z=p; return ((-y)%D,(x-6)%D,(z+3+y)%D)
def ai(p,D): x,y,z=p; return (x%D,(y+x)%D,(z-1)%D)
def cycles(perm, pts):
    seen=set(); c=0
    for p in pts:
        if p in seen: continue
        c+=1; q=p
        while q not in seen: seen.add(q); q=perm(q)
    return c
for D in list(range(1,16,2))+[2,4,6]:
    pts=[(x,y,z) for x in range(D) for y in range(D) for z in range(D)]
    # orbits of the group generated by a1,a2
    left=set(pts); orbs=[]
    while left:
        s=left.pop(); orb={s}; st=[s]
        while st:
            q=st.pop()
            for f in (a1,a2,ai):
                r=f(q,D)
                if r not in orb: orb.add(r); st.append(r)
        left-=orb; orbs.append(orb)
    gs=[]
    for orb in orbs:
        n=len(orb); o=sorted(orb)
        c1=cycles(lambda q:a1(q,D),o); c2=cycles(lambda q:a2(q,D),o); ci=cycles(lambda q:ai(q,D),o)
        gs.append(Fr(2-(c1+c2+ci-n),2))
    gform=Fr(5*D**3-12*D**2-17*D+24,24); g0=Fr(5*D**3-12*D**2-81*D+216,216); g1=Fr(5*D**3-12*D**2-9*D+27,27)
    print(f"D={D:2d} orbit sizes={sorted(len(o) for o in orbs)} genera={sorted(gs)} g(D)={gform} g0,g1={g0},{g1} sum(g)-(#orb-1)={sum(gs)-(len(orbs)-1)}")
