#!/usr/bin/env python3
"""ref52_partB_group.py -- referee's independent checks for note 52_, Part B (S6 monodromy).

Pure-integer Python (no numpy/sympy), written independently of s6_monodromy_checks.py.
Method differs from the note: instead of BFS in GL4(Z/D) and the SL2(Z) presentation, it
 (1) rebuilds T1, T2 from the IMAGES listed in manuscript (2.2) (column j = image of basis vector j) and Q0 from Lemma 2.8;
 (2) decomposes every element of G_Z as L_M h(p,r,s) and defines the character
        Phi(L_M h(p,r,s)) = s - 6(p^2+pr+r^2) + ab(M)  (mod 12),
     ab = abelianization SL2(Z) -> Z/12 normalized by ab([[1,1],[0,1]]) = 1, computed by a Euclidean word
     decomposition over Z (and cross-checked against a lookup on SL2(Z/12));
 (3) proves G = ker(Phi) constructively: G <= ker Phi (Phi(T1) = Phi(T2) = 0, Phi a homomorphism), and for random
     g in G_Z an explicit word in T1, T2 times the central transvection t^k, k = Phi(g), is produced and multiplied out;
 (4) compares, as SETS, G mod 12 (BFS with integer-encoded matrices, generators T1, T2 only) with the predicted set
     {L_M h(p,r,s) mod 12 : Phi = 0} built directly from the formula;
 (5) records the structural consequences: G normal, G_Z/G = Z/12 cyclic generated by the central transvection
     t_gamma = h(0,0,1); T0 = L_{T^-1} t_gamma; G n Levi = commutator subgroup; congruence level exactly 12;
     H' = <c, T2 c T2^-1> = [G_Z, Heis(Z)]; non-splitting of 1 -> H' -> G -> SL2(Z) -> 1 (sanity search);
 (6) ES-09 affine orbits on {gamma-hat = 1} of Lambda/D for all D <= 24 via union-find, for G and for G_Z, as full
     partitions, against the closed formula (orbits <-> gcd(b, c, gcd(D,6))).
"""
import random, itertools, math, sys, time
t_start = time.time()
random.seed(20260927)
results = []
def check(name, cond):
    ok = bool(cond); results.append((name, ok)); print(("PASS" if ok else "FAIL") + "  " + name, flush=True)

# ---------- integer 4x4 / 2x2 matrix helpers (lists of lists) ----------
def mul(A, B):
    n, m, k = len(A), len(B[0]), len(B)
    return [[sum(A[i][l]*B[l][j] for l in range(k)) for j in range(m)] for i in range(n)]
def tr(A): return [list(r) for r in zip(*A)]
def eye(n): return [[1 if i == j else 0 for j in range(n)] for i in range(n)]
def from_images(imgs):  # imgs[j] = image of basis vector j, as a coordinate list -> matrix with these columns
    return tr(imgs)
def inv_unimodular4(A):
    # exact inverse via adjugate (det = +-1 for all our matrices)
    import fractions
    n = 4
    M = [[fractions.Fraction(A[i][j]) for j in range(n)] + [fractions.Fraction(1 if i == j else 0) for j in range(n)] for i in range(n)]
    for col in range(n):
        piv = next(r for r in range(col, n) if M[r][col] != 0)
        M[col], M[piv] = M[piv], M[col]
        pv = M[col][col]
        M[col] = [x / pv for x in M[col]]
        for r in range(n):
            if r != col and M[r][col] != 0:
                f = M[r][col]
                M[r] = [a - f*b for a, b in zip(M[r], M[col])]
    Inv = [[M[i][n+j] for j in range(n)] for i in range(n)]
    assert all(x.denominator == 1 for row in Inv for x in row)
    return [[int(x) for x in row] for row in Inv]
def mpow(A, e):
    R = eye(len(A))
    if e < 0:
        A = inv_unimodular4(A) if len(A) == 4 else inv2(A); e = -e
    for _ in range(e): R = mul(R, A)
    return R
def inv2(M): a, b, c, d = M[0][0], M[0][1], M[1][0], M[1][1]; det = a*d - b*c; assert det == 1; return [[d, -b], [-c, a]]

# ---------- (1) the data, re-entered from the manuscript text ----------
# basis order (gamma, u, w, delta) = coordinates 0..3
g_, u_, w_, d_ = [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]
def lin(*terms):
    v = [0,0,0,0]
    for coef, vec in terms:
        v = [a + coef*b for a, b in zip(v, vec)]
    return v
# (2.2): T1 gamma = gamma, T1 u = -u - w, T1 w = -6 gamma + u, T1 delta = 2 gamma + u + w + delta
T1 = from_images([g_, lin((-1,u_),(-1,w_)), lin((-6,g_),(1,u_)), lin((2,g_),(1,u_),(1,w_),(1,d_))])
# (2.2): T2 gamma = gamma, T2 u = 6 gamma + w, T2 w = -u, T2 delta = -3 gamma + u + delta
T2 = from_images([g_, lin((6,g_),(1,w_)), lin((-1,u_)), lin((-3,g_),(1,u_),(1,d_))])
# Lemma 2.8: Q0(gamma, delta) = 1, Q0(u, w) = 6, other basis pairings 0 (Gram matrix Q[i][j] = Q0(e_i, e_j))
Q0 = [[0,0,0,1],[0,0,6,0],[0,-6,0,0],[-1,0,0,0]]
I4 = eye(4)
# printed matrices of Definition 2.1 (rows as printed)
check("(1) T1, T2 built from the images in (2.2) equal the printed matrices of Definition 2.1",
      T1 == [[1,0,-6,2],[0,-1,1,1],[0,-1,0,1],[0,0,0,1]] and T2 == [[1,6,0,-3],[0,0,-1,1],[0,1,0,0],[0,0,0,1]])
check("(1) T1^3 = I, T2^4 = I, T1 != I, T2^2 != I", mpow(T1,3) == I4 and mpow(T2,4) == I4 and T1 != I4 and mpow(T2,2) != I4)
def preserves(g): return mul(mul(tr(g), Q0), g) == Q0
check("(1) T1, T2 preserve Q0 (g^T Q0 g = Q0) and fix gamma", preserves(T1) and preserves(T2) and [r[0] for r in T1] == g_ and [r[0] for r in T2] == g_)
T0 = inv_unimodular4(mul(T1, T2))
N = [[T0[i][j] - I4[i][j] for j in range(4)] for i in range(4)]
check("(1) T0 = (T1 T2)^-1: N = T0 - I has N gamma = N u = 0, N w = -u, N delta = gamma (manuscript Lemma 2.2(iii))",
      tr(N) == [[0,0,0,0],[0,0,0,0],[0,-1,0,0],[1,0,0,0]])

# ---------- (2) Levi / Heisenberg decomposition and the character Phi ----------
def L(M):
    A = eye(4); A[1][1], A[1][2], A[2][1], A[2][2] = M[0][0], M[0][1], M[1][0], M[1][1]; return A
def h(p, r, s):  # gamma->gamma, u->u-6r gamma, w->w+6p gamma, delta->delta+p u+r w+s gamma
    return from_images([g_, lin((1,u_),(-6*r,g_)), lin((1,w_),(6*p,g_)), lin((1,d_),(p,u_),(r,w_),(s,g_))])
def decompose(g):
    """g in G_Z -> (M, (p,r,s)) with g = L(M) h(p,r,s); asserts membership in G_Z."""
    assert preserves(g) and [row[0] for row in g] == g_
    M = [[g[1][1], g[1][2]], [g[2][1], g[2][2]]]
    hh = mul(L(inv2(M)), g)
    p, r, s = hh[1][3], hh[2][3], hh[0][3]
    assert hh == h(p, r, s), "not of the form L_M h"
    return M, (p, r, s)
S2 = [[0,-1],[1,0]]; T_ = [[1,1],[0,1]]
def ab_euclid(M):
    """abelianization SL2(Z) -> Z/12 with ab(T) = 1, ab(S) = 9, via Euclidean reduction over Z."""
    M = [row[:] for row in M]; acc = 0      # invariant: original = X * M_current, acc = ab(X)
    while M[1][0] != 0:
        a, c = M[0][0], M[1][0]
        k = -(a // c) if c != 0 else 0      # T^k M has top-left a + k c, reduced mod c
        M = [[M[0][0] + k*M[1][0], M[0][1] + k*M[1][1]], [M[1][0], M[1][1]]]; acc -= k   # M_old = T^-k M_new
        # now swap with S: M_new = S M  =>  M_old = S^-1 M_new
        M = [[-M[1][0], -M[1][1]], [M[0][0], M[0][1]]]; acc -= 9
    # M = [[e, b], [0, e]], e = +-1
    e, b = M[0][0], M[0][1]
    assert M[1][1] == e and e in (1, -1)
    return (acc + (b if e == 1 else 6 - b)) % 12      # -T^{-b} = S^2 T^{-b}: ab = 18 - b
# lookup of ab on SL2(Z/12) by BFS from S, T: also proves ab factors through SL2(Z/12) (no conflicting values)
def key2(M): return tuple(x % 12 for x in (M[0][0], M[0][1], M[1][0], M[1][1]))
ab12 = {key2(eye(2)): 0}; frontier = [eye(2)]; conflict = False
gens2 = [(S2, 9), (T_, 1)]
while frontier:
    nxt = []
    for M in frontier:
        for G2, val in gens2:
            P = [[x % 12 for x in row] for row in mul(M, G2)]
            k = key2(P); v = (ab12[key2(M)] + val) % 12
            if k in ab12:
                if ab12[k] != v: conflict = True
            else:
                ab12[k] = v; nxt.append(P)
    frontier = nxt
check(f"(2) ab is well defined on SL2(Z/12) (BFS over {len(ab12)} = |SL2(Z/12)| = 1152 elements, no conflict): the abelianization character is a congruence character of level 12",
      not conflict and len(ab12) == 1152)
def rand_sl2(nsteps=12):
    M = eye(2)
    for _ in range(nsteps):
        M = mul(M, random.choice([S2, T_, inv2(T_), inv2(S2)]))
    return M
check("(2) ab via Euclid over Z agrees with the SL2(Z/12) lookup on 2000 random elements; ab(T) = 1, ab(S) = 9, ab(-I) = 6",
      all(ab_euclid(M) == ab12[key2(M)] for M in (rand_sl2(random.randint(1, 40)) for _ in range(2000)))
      and ab_euclid(T_) == 1 and ab_euclid(S2) == 9 and ab_euclid([[-1,0],[0,-1]]) == 6)
def qf(p, r): return p*p + p*r + r*r
def Phi(g):
    M, (p, r, s) = decompose(g)
    return (s - 6*qf(p, r) + ab_euclid(M)) % 12
M1, hp1 = decompose(T1); M2, hp2 = decompose(T2)
check(f"(2) T1 = L_R h{hp1}, T2 = L_S h{hp2} with R = {M1}, S = {M2}  (expected h(-1,0,2), h(0,-1,-3))",
      hp1 == (-1, 0, 2) and hp2 == (0, -1, -3) and M1 == [[-1,1],[-1,0]] and M2 == [[0,-1],[1,0]])
check("(2) Phi(T1) = Phi(T2) = 0, Phi(t_gamma) = Phi(h(0,0,1)) = 1, Phi(L_T) = 1", Phi(T1) == 0 and Phi(T2) == 0 and Phi(h(0,0,1)) == 1 and Phi(L(T_)) == 1)
M0, hp0 = decompose(T0)
check(f"(2) the cusp monodromy is T0 = L_(T^-1) t_gamma: Levi part {M0}, Heisenberg part h{hp0}", M0 == [[1,-1],[0,1]] and hp0 == (0,0,1))
GZgens = [L(S2), L(T_), h(1,0,0), h(0,1,0), h(0,0,1)]
GZgens_all = GZgens + [inv_unimodular4(x) for x in GZgens]
def rand_GZ(n):
    g = eye(4)
    for _ in range(n): g = mul(g, random.choice(GZgens_all))
    return g
ok_hom = True
for _ in range(400):
    a = rand_GZ(random.randint(1, 25)); b = rand_GZ(random.randint(1, 25))
    if Phi(mul(a, b)) != (Phi(a) + Phi(b)) % 12: ok_hom = False; break
check("(2) Phi is a homomorphism G_Z -> Z/12 (400 random pairs of words of length <= 25 in the G_Z generators)", ok_hom)
Gw = [T1, T2, inv_unimodular4(T1), inv_unimodular4(T2)]
def rand_G(n):
    g = eye(4)
    for _ in range(n): g = mul(g, random.choice(Gw))
    return g
check("(2) Phi vanishes on 1000 random words (length <= 60) in T1^{+-1}, T2^{+-1}", all(Phi(rand_G(random.randint(1, 60))) == 0 for _ in range(1000)))

# ---------- (3) constructive membership: G_Z = disjoint union of G t^k, k = Phi(g) ----------
T1i, T2i = inv_unimodular4(T1), inv_unimodular4(T2)
c = mul(mul(T1, mpow(T2, 2)), mul(T1i, mpow(T2i, 2)))          # [T1, T2^2]
cp = mul(mul(T2, c), T2i)
check("(3) c = [T1, T2^2] = h(1,0,-6), c' = T2 c T2^-1 = h(0,1,6), [c, c'] = h(0,0,12)",
      c == h(1,0,-6) and cp == h(0,1,6) and mul(mul(c, cp), mul(inv_unimodular4(c), inv_unimodular4(cp))) == h(0,0,12))
liftS = T2; liftT = mul(mul(T2, T2), mul(T1, T2i))                 # pi(T2 T2 T1 T2^-1) = S S R S^-1 = T
check("(3) the lifts: pi(T2) = S, pi(T2^2 T1 T2^-1) = T = [[1,1],[0,1]]", decompose(liftS)[0] == S2 and decompose(liftT)[0] == T_)
def word_for_sl2(M):
    """return a list of (symbol, exponent) with product = M, symbols 'S', 'T', 'Z' (= -I = S^2)."""
    M = [row[:] for row in M]; left = []     # original = product(left) * M_current
    while M[1][0] != 0:
        a, cc = M[0][0], M[1][0]
        k = -(a // cc)
        M = [[M[0][0] + k*M[1][0], M[0][1] + k*M[1][1]], [M[1][0], M[1][1]]]; left.append(('T', -k))
        M = [[-M[1][0], -M[1][1]], [M[0][0], M[0][1]]]; left.append(('S', -1))
    e, b = M[0][0], M[0][1]
    if e == 1: left.append(('T', b))
    else: left.append(('Z', 1)); left.append(('T', -b))
    return left
def lift_word(word):
    g = eye(4)
    for sym, e in word:
        base = {'S': liftS, 'T': liftT, 'Z': mpow(T2, 2)}[sym]
        g = mul(g, mpow(base, e))
    return g
def express(g):
    """g in G_Z -> (w, p, r, m, k) with g = w * c^p c'^r [c,c']^m * t^k, w a word in T1, T2; returns the product too."""
    M, _ = decompose(g)
    w = lift_word(word_for_sl2(M))
    hh = mul(inv_unimodular4(w), g)
    Mh, (p, r, s) = decompose(hh)
    assert Mh == eye(2)
    k = (s - 6*qf(p, r)) % 12
    s1 = s - k                                                   # h(p,r,s1) in H'
    base = -6*p + 6*r + 6*p*r                                    # c^p c'^r = h(p, r, base)
    assert (s1 - base) % 12 == 0
    m = (s1 - base) // 12
    prod = mul(mul(w, mpow(c, p)), mul(mpow(cp, r), mul(mpow(h(0,0,12), m), mpow(h(0,0,1), k))))
    return prod, k
ok_expr = True; ks = set()
for _ in range(300):
    g = rand_GZ(random.randint(1, 30))
    prod, k = express(g)
    ks.add(k)
    if prod != g or k != Phi(g): ok_expr = False; break
check(f"(3) 300 random g in G_Z: g = (word in T1,T2) * t_gamma^k with k = Phi(g), verified by multiplying out; k takes {len(ks)} values",
      ok_expr and len(ks) == 12)
check("(3) hence G = ker Phi, [G_Z : G] = 12, G normal, G_Z/G = Z/12 generated by the central t_gamma; G n <t_gamma> = <t_gamma^12>",
      ok_expr and all(Phi(mpow(h(0,0,1), k)) == k % 12 for k in range(-13, 14)))
# t_gamma is central in G_Z
tg = h(0,0,1)
check("(3) t_gamma = h(0,0,1) (delta -> delta + gamma) is central in G_Z", all(mul(tg, x) == mul(x, tg) for x in GZgens))
# G n Heis = H'
def in_Hp(p, r, s): return s % 6 == 0 and (s//6 - qf(p, r)) % 2 == 0
check("(3) G n Heis = ker(phi) = H' : phi(h(p,r,s)) = s - 6(p^2+pr+r^2) = 0 mod 12 <=> 6|s and s/6 = p^2+pr+r^2 mod 2 (box |p|,|r|<=6, |s|<=40)",
      all(((s - 6*qf(p, r)) % 12 == 0) == in_Hp(p, r, s) for p in range(-6, 7) for r in range(-6, 7) for s in range(-40, 41)))
# G n Levi = commutator subgroup of SL2(Z): L_M in G iff ab(M) = 0; e.g. [[2,1],[1,1]] = commutator
comm = mul(mul(S2, T_), mul(inv2(S2), inv2(T_)))
check("(3) G n Levi = L(SL2(Z)'): L_M in G iff ab(M) = 0; L_T not in G, L_{[S,T]} in G, L_{T^12} in G",
      Phi(L(T_)) != 0 and Phi(L(comm)) == 0 and Phi(L(mpow(T_, 12))) == 0)
# congruence level: Phi depends only on g mod 12; K_6 and K_4 are not in G
K12gens = [L(mpow(T_, 12)), L(mpow(tr(T_), 12)), h(12,0,0), h(0,12,0), h(0,0,12)]
def rand_K12(n):
    x = eye(4)
    for _ in range(n):
        y = rand_GZ(random.randint(0, 12)); k = random.choice(K12gens)
        x = mul(x, mul(mul(y, k), inv_unimodular4(y)))
    return x
check("(3) congruence: Phi = 0 on 200 random elements of the principal congruence subgroup K_12 (products of G_Z-conjugates of level-12 generators); "
      "h(0,0,6) in K_6 and h(0,0,4) in K_4 are not in G: the congruence level of G is exactly 12",
      all(Phi(rand_K12(random.randint(1, 4))) == 0 for _ in range(200)) and Phi(h(0,0,6)) == 6 and Phi(h(0,0,4)) == 4)
# H' = [G_Z, Heis(Z)]: commutators [L_M, h] and [h, h'] lie in H' and the ones below generate it
def commu(a, b): return mul(mul(a, b), mul(inv_unimodular4(a), inv_unimodular4(b)))
cm = [commu(L(M), hx) for M in (S2, T_, inv2(T_), mul(S2, T_)) for hx in (h(1,0,0), h(0,1,0), h(0,0,1), h(1,1,0))]
cm_ok = all(in_Hp(*decompose(x)[1]) and decompose(x)[0] == eye(2) for x in cm)
proj = sorted({decompose(x)[1][:2] for x in cm})
det_gcd = 0
for a_ in proj:
    for b_ in proj:
        det_gcd = math.gcd(det_gcd, a_[0]*b_[1] - a_[1]*b_[0])
x1 = next(x for x in cm if decompose(x)[1][:2] == (1, 0)); x2 = next(x for x in cm if decompose(x)[1][:2] == (-1, 1))
check(f"(3) [G_Z, Heis] <= H' (all {len(cm)} sampled commutators [L_M, h] lie in H'); their (p,r)-projections {proj} generate Z^2 (gcd of 2x2 minors = {det_gcd}); "
      f"[[L_T,h(0,1,0)], [L_S,h(1,0,0)]] = h{decompose(commu(x1, x2))[1]}: so the normal subgroup [G_Z, Heis(Z)] projects onto Z^2, contains h(0,0,12), hence equals H'",
      cm_ok and det_gcd == 1 and decompose(commu(x1, x2))[1] == (0, 0, 12))
# non-splitting sanity: order-2 elements of G over -I are L_{-I} h(x,0) with q(x) odd; none commutes with an element of G over R
negI = [[-1,0],[0,-1]]
invols = [mul(L(negI), h(p, r, 0)) for p in range(-3, 4) for r in range(-3, 4) if qf(p, r) % 2 == 1]
check("(3) the order-2 elements of G over -I include T2^2 = L_{-I} h(-1,-1,0); all L_{-I}h(x,0), q(x) odd, are in G and have order 2",
      mpow(T2, 2) == mul(L(negI), h(-1,-1,0)) and all(Phi(x) == 0 and mul(x, x) == I4 for x in invols))
overR = [mul(L(M1), h(p, r, s)) for p in range(-4, 5) for r in range(-4, 5) for s in range(-30, 31) if Phi(mul(L(M1), h(p, r, s))) == 0]
none_commute = all(mul(a, b) != mul(b, a) for a in invols for b in overR)
check(f"(3) non-split sanity: none of {len(overR)} elements of G over R (box) commutes with any of the {len(invols)} involutions over -I; "
      "proof: conjugation gives L_(-I) h(R(x-2y),0), needing R^-1 x = x mod 2, impossible for x != 0 mod 2", none_commute)

# ---------- (4) G mod 12 as a set, versus the formula ----------
def enc(A, D):  # integer key of a 4x4 matrix mod D (only the 9 non-constant entries matter, but encode all 16)
    k = 0
    for row in A:
        for x in row:
            k = k*D + (x % D)
    return k
def bfs_mod(gens, D):
    gm = [[[x % D for x in row] for row in g] for g in gens]
    start = [[x % D for x in row] for row in I4]
    seen = {enc(start, D)}; frontier = [start]
    while frontier:
        nxt = []
        for A in frontier:
            for g in gm:
                P = [[sum(A[i][l]*g[l][j] for l in range(4)) % D for j in range(4)] for i in range(4)]
                k = enc(P, D)
                if k not in seen: seen.add(k); nxt.append(P)
        frontier = nxt
    return seen
t0 = time.time()
G12 = bfs_mod([T1, T2], 12)       # finite group: the monoid generated by T1, T2 is the group
pred = set()
for Mk, abv in ab12.items():
    M = [[Mk[0], Mk[1]], [Mk[2], Mk[3]]]
    LM = L(M)
    for p in range(12):
        for r in range(12):
            s = (6*qf(p, r) - abv) % 12
            pred.add(enc(mul(LM, h(p, r, s)), 12))
check(f"(4) G mod 12 (BFS: {len(G12)} elements, {time.time()-t0:.0f}s) equals the predicted set {{L_M h(p,r,s) mod 12 : s = 6q(p,r) - ab(M)}} ({len(pred)} = 1152*144 elements)",
      G12 == pred and len(pred) == 1152*144)
# index of G mod D in G_Z mod D: |G_Z mod D| = |SL2(Z/D)| * D^3 (Levi image SL2(Z/D), Heisenberg image (p,r,s) mod D),
# so index = |SL2(Z/D)| D^3 / |G mod D|; predicted gcd(D,12) since Phi(K_D) = gcd(D,12) Z/12.
def sl2_order(D):
    o = D**3
    for pp in range(2, D+1):
        if D % pp == 0 and all(pp % q for q in range(2, pp)):
            o = o * (pp*pp - 1) // (pp*pp)
    return o
idx = {}
for D in (2, 3, 4, 6, 8, 9, 12):
    GD = G12 if D == 12 else bfs_mod([T1, T2], D)
    tot = sl2_order(D) * D**3
    idx[D] = (tot // len(GD), tot % len(GD))
check(f"(4) [G_Z mod D : G mod D] by independent BFS of G mod D (D = 2,3,4,6,8,9,12): {[idx[D][0] for D in idx]}; equals gcd(D,12) in every case (Phi(K_D) = gcd(D,12)Z/12)",
      all(idx[D][1] == 0 and idx[D][0] == math.gcd(D, 12) for D in idx))

# ---------- (6) ES-09 affine orbits, all D <= 24, full partitions ----------
def dual(g): return tr(inv_unimodular4(g))
A1, A2 = dual(T1), dual(T2)
check("(6) dual matrices A_j = (T_j^-1)^T are the manuscript's A1, A2 (Lemma 2.4)",
      A1 == [[1,0,0,0],[6,0,1,0],[-6,-1,-1,0],[-2,1,0,1]] and A2 == [[1,0,0,0],[0,0,-1,0],[-6,1,0,0],[3,0,1,1]])
def orbit_partition(gens, D):
    n = D**3
    parent = list(range(n))
    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]; i = parent[i]
        return i
    def idxp(b, cc, d): return (b % D)*D*D + (cc % D)*D + (d % D)
    for b in range(D):
        for cc in range(D):
            for d in range(D):
                v = [1, b, cc, d]
                for g in gens:
                    wv = [sum(g[i][j]*v[j] for j in range(4)) for i in range(4)]
                    assert wv[0] % D == 1 % D
                    ra, rb = find(idxp(b, cc, d)), find(idxp(wv[1], wv[2], wv[3]))
                    if ra != rb: parent[ra] = rb
    return [find(i) for i in range(n)]
def predicted_label(b, cc, D):
    e = math.gcd(D, 6)
    return math.gcd(math.gcd(b % e, cc % e), e) if e > 1 else 1
all_ok = True; report = []
for D in range(2, 25):
    part_G = orbit_partition([A1, A2], D)
    part_GZ = orbit_partition([dual(x) for x in GZgens], D)
    # compare partitions: same blocks
    def blocks(part):
        bl = {}
        for i, rt in enumerate(part): bl.setdefault(rt, []).append(i)
        return sorted(tuple(v) for v in bl.values())
    bG, bGZ = blocks(part_G), blocks(part_GZ)
    labels = {}
    for i in range(D**3):
        b, cc = (i // (D*D)), (i // D) % D
        labels.setdefault(part_G[i], set()).add(predicted_label(b, cc, D))
    lab_ok = all(len(v) == 1 for v in labels.values()) and len({next(iter(v)) for v in labels.values()}) == len(labels)
    sizes = sorted(len(x) for x in bG)
    e = math.gcd(D, 6)
    # predicted sizes: D^3/e^2 * #{v in (Z/e)^2 : gcd(v, e) = g} over g | e
    pred_sizes = sorted(D**3 // (e*e) * sum(1 for x in range(e) for y in range(e) if math.gcd(math.gcd(x, y), e) == gg) for gg in range(1, e+1) if e % gg == 0)
    ok = (bG == bGZ) and lab_ok and sizes == pred_sizes
    all_ok &= ok
    report.append((D, sizes))
for D, sz in report:
    print(f"      D = {D:2d}: orbit sizes of G (= those of G_Z) on the affine hyperplane: {sz}")
check("(6) for every D = 2..24: G and G_Z have identical orbit PARTITIONS, and the orbits are exactly the classes of gcd(b, c, gcd(D,6)) "
      "(b, c the u-hat, w-hat coordinates), with sizes D^3/e^2 * #{v in (Z/e)^2 : content g}, e = gcd(D,6)", all_ok)
print(f"\nsummary: {len(results)} checks, {sum(o for _, o in results)} PASS, {len(results) - sum(o for _, o in results)} FAIL; {time.time()-t_start:.0f}s")
