"""Exact primitive, support and mixed-product maps, DN1–DN23 and NI17–NI24."""
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

P=Path(__file__).resolve().parent/'figures'
plt.rcParams.update({'font.family':'DejaVu Sans','svg.fonttype':'none'})
ink='#183047'; blue='#245eaa'; green='#157564'; red='#ad3545'

def setup(title,subtitle):
    fig,ax=plt.subplots(figsize=(16,12))
    fig.patch.set_facecolor('#fcfcfa')
    fig.subplots_adjust(left=.025,right=.99,bottom=.025,top=.975)
    ax.set(xlim=(0,16),ylim=(0,12));ax.axis('off')
    ax.text(.25,11.8,title,fontsize=23,weight='bold',color=ink,va='top')
    ax.text(.25,11.1,subtitle,fontsize=17,color=ink)
    return fig,ax
def box(ax,x,y,w,h,color):
    ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=.12',fc='white',ec=color,lw=1.7))
def txt(ax,x,y,s,fs=18,color=ink): ax.text(x,y,s,fontsize=fs,color=color)
def save(fig,name):
    for ext in ('png','svg'):fig.savefig(P/f'{name}.{ext}',dpi=150,facecolor=fig.get_facecolor())
    plt.close(fig)

fig,ax=setup('A primitive from the tau corner reaches dual numbers',r'$S=\{\tau\}\sqcup\mathbb{Z}^{\bullet},\quad e=0^{\bullet}\ne\tau,\quad\eta=[1^{\bullet}]-[e]$')
box(ax,.3,7.2,15.1,3.3,blue)
txt(ax,.6,10.04,'The exact support algebra and its first-order quotient',18,blue)
txt(ax,.6,9.27,r'$\mathcal{A}_+=\mathbb{Z}[(S,+)]\cong\mathbb{Z}\times\mathbb{Z}[z^{\pm1}],\quad[\tau]\mapsto(1,1),\quad[n^{\bullet}]\mapsto(0,z^n)$',21)
txt(ax,.6,8.51,r'$\mathcal{J}=\ker Q=0\times(z-1)T,\qquad\mathcal{A}_+/\mathcal{J}^{2}\cong\mathbb{Z}\times D,\quad D=\mathbb{Z}[\varepsilon]/(\varepsilon^{2})$',21)
txt(ax,.6,7.71,r'$\eta\mapsto(0,\varepsilon),\qquad[e]\mapsto(0,1),\qquad[\tau]-[e]\mapsto(1,0)$',21)
box(ax,.3,3.9,15.1,2.7,green)
txt(ax,.6,6.13,'The retained mixed product gives the same defining ideal',18,green)
txt(ax,.6,5.38,r'$R=\mathbb{Z}[t^{\pm1},u^{\pm1}],\quad j=(t-1)(u-1),\quad W\cong jR,\quad\mu(t)=\mu(u)=z$',21)
txt(ax,.6,4.61,r'$0\longrightarrow j(t-u)R\longrightarrow W\longrightarrow(z-1)^2T\longrightarrow0,\qquad T/\mu(W)\cong D$',21)
box(ax,.3,.95,7.25,2.35,red);box(ax,8,.95,7.4,2.35,blue)
txt(ax,.6,2.85,'Two specified infinitesimal routes',17,red)
txt(ax,.6,2.14,r'$D\hookrightarrow R/j^2,\quad\varepsilon\mapsto\overline{j}$',20)
txt(ax,.6,1.48,r'$(R/j)/(t-u)\cong D,\quad t-1\mapsto\varepsilon$',19)
txt(ax,8.3,2.85,'The natural quotient is a different map',16,blue)
txt(ax,8.3,2.14,r'$R/j^2\longrightarrow(R/j)/(t-u),\quad\overline{j}\mapsto0$',19)
txt(ax,8.3,1.48,r'$\ker=(j,t-u)/(j^2)$',20)
txt(ax,.4,.32,'Full proofs: DN1–DN21. Standard infinitesimal neighbourhood: Stacks 05YW; exact derivative comparison: DN22–DN23.',11.7)
save(fig,'14_primitive_dual_numbers')

fig,ax=setup('Retaining support changes the module, with exact maps',r'$R_N=\epsilon_N f_N e_N^{\dagger_{G_N}},\quad \Pi_N=e_Ne_N^{\dagger_{G_N}}+f_Nf_N^{\dagger_{G_N}},\quad H_N=\ker \Pi_N$')
box(ax,.3,7.1,15.1,3.4,blue)
txt(ax,.6,10.05,'A faithful receiver for the full support quotient',18,blue)
txt(ax,.6,9.3,r'$Q_{\mathbb{C}}=\mathbb{C}\times D_{\mathbb{C}}\longrightarrow\mathrm{End}_{\mathbb{C}}(E),\quad(k,a+b\eta)\mapsto k(I-\Pi_N)+a\Pi_N+bR_N$',20)
txt(ax,.6,8.53,r'$[\tau]\mapsto I,\quad[e]\mapsto \Pi_N,\quad[n^{\bullet}]\mapsto \Pi_N+nR_N,\quad[1^{\bullet}]-[e]\mapsto R_N$',21)
txt(ax,.6,7.69,r'$E\cong H_N\oplus D_{\mathbb{C}}\quad\mathrm{as}\ Q_{\mathbb{C}}\mathrm{-module};\qquad E\ \mathrm{is\ finite\ projective}$',21)
box(ax,.3,3.8,15.1,2.7,red)
txt(ax,.6,6.07,'Restriction along the stated inclusion produces the exact Tor object',18,red)
txt(ax,.6,5.31,r'$D_{\mathbb{C}}\hookrightarrow Q_{\mathbb{C}},\quad a+b\eta\mapsto(a,a+b\eta)$',22)
txt(ax,.6,4.55,r'$\mathrm{Tor}^{D_{\mathbb{C}}}_i(\mathbb{C},E)\cong\ker R_N/\mathrm{im}R_N\cong H_N=\ker W_N\quad(i\geq1)$',21)
box(ax,.3,.95,15.1,2.3,green)
txt(ax,.6,2.8,'The cubic root factors through both support sectors',18,green)
txt(ax,.6,2.04,r'$\mathrm{span}(e_N,f_N)\ \rightleftarrows\ H_N,\quad \|g\|_{G_N}=1$',21)
txt(ax,.6,1.32,r'$T_g^2=R_N,\quad T_g^3=0;\qquad\mathrm{reverse\ composite}=0$',21)
txt(ax,.4,.32,'Proofs: NI14–NI24. Every adjoint uses the original metric. D-module norm on the plane: |a|² + epsilon_N² |b|².',11.8)
save(fig,'16_support_module_defect')

fig,ax=setup('Two idempotent fibres meet at the original infinitesimal',r'$F(s)=R_N+sP_e,\quad P_e=e_Ne_N^{\dagger_{G_N}},\quad F(s)^2=sF(s),\quad\mathcal{A}=\mathbb{C}[s,z]/(z(z-s))$')
box(ax,.3,6.5,6.1,4.0,blue)
txt(ax,.6,10.03,'Scheme and its map to the s-line',17,blue)
ax.plot([1,5.8],[7.75,7.75],color=blue,lw=2.5)
ax.plot([1.3,5.5],[6.9,9.7],color=green,lw=2.5)
ax.plot([2.575,2.575],[6.85,9.65],color=red,lw=1.4,ls='--')
ax.scatter([2.575],[7.75],color=red,s=80,zorder=3)
txt(ax,4.8,7.3,r'$z=0$',16,blue);txt(ax,4.6,9.55,r'$z=s$',16,green)
txt(ax,1.35,6.95,r'$s=0$',16,red)
txt(ax,.6,6.65,'The point symbol marks support; the fibre retains z²=0.',10.4)
box(ax,6.9,6.5,8.5,4.0,green)
txt(ax,7.2,10.03,'The fibres and their exact representations',17,green)
txt(ax,7.2,9.17,r'$s=\sigma\ne0:\quad\mathcal{A}_{\sigma}\cong\mathbb{C}\times\mathbb{C}$',22)
txt(ax,7.2,8.38,r'$z/\sigma,\ 1-z/\sigma\quad\mathrm{are\ complementary\ idempotents}$',18)
txt(ax,7.2,7.58,r'$s=0:\quad\mathcal{A}_0=D_{\mathbb{C}},\quad z\mapsto R_N$',22)
txt(ax,7.2,6.86,'Every fibre has dimension 2; the family is free over C[s].',13)
box(ax,.3,3.7,15.1,2.2,red)
txt(ax,.6,5.48,'The metric cost is exact; no idempotent is discarded',18,red)
txt(ax,.6,4.68,r'$\|\Pi_0(\sigma)\|=\|\Pi_1(\sigma)\|=\sqrt{1+\epsilon_N^2/|\sigma|^2},\qquad\|F(\sigma)-R_N\|=|\sigma|$',23)
txt(ax,.6,4.01,'The algebraic eigenprojections diverge; the actual boundary operator converges in the original metric.',13.5)
box(ax,.3,.95,15.1,2.2,blue)
txt(ax,.6,2.73,'Along real s the complete original current and its observation are fixed',18,blue)
txt(ax,.6,1.99,r'$M(s)=C_N+F(s),\quad i(M(s)-M(s)^{\dagger})=W_N,\quad O_N^{\dagger}W_NO_N=\epsilon_N U_NJ_2U_N^*$',20)
txt(ax,.6,1.3,'Current bounds transfer by equality. The Hermitian part and the full spectral problem retain their separate formulas.',13.3)
txt(ax,.4,.32,'Proofs: ID1–ID18; changing spectrum with fixed current: ID24. The diagram shows a real section of the stated complex scheme.',11.6)
save(fig,'17_idempotent_current')
